### ISSUE TITLE
进入暮色前置任务无法完成

### ISSUE THREAD

**Issue by Yricky** [Kasualix/DTD#1]
击杀Herobrine后无法完成FTB任务

**Comment by Kasualix** [comment]
ftb的问题一直在
群友报告过了
work on it

**Comment by Kasualix** [comment]
今晚更新，尝试修掉（over and over again）

**Comment by Kasualix** [comment]
在解决之前，你可以指令/gamestage add [你的名字] twotwiliforest

**Comment by Yricky** [comment]
进入暮色任务本身也无法完成

**Comment by Kasualix** [comment]
那个是维度设错了（

**Comment by Yricky** [comment]
编辑完成后，完成了后续任务也无法进入古代，提示时光机未做好准备

**Comment by Kasualix** [comment]
暮色最终boss是埃诺斯，要干掉它才能进

**Comment by Kasualix** [comment]
其实主要是ftbq的实体判定出问题了，我现在正在把它都换成阶段判定，（应该）就没问题了

**Comment by Kasualix** [comment]
"/remake ftbq".txt(

**Comment by Kasualix** [comment]
准备更新
如果之后ftbq又出问题，欢迎再open这个issue~
