### ISSUE TITLE
服务端进不去，有问题

### ISSUE THREAD

**Issue by 2080129305** [Kasualix/DTD#16]
1.7还能进，1.8不行了
链接：https://pan.baidu.com/s/1zYsG9EJB03DmfgypKFSRwQ?pwd=1111 
提取码：1111 
--来自百度网盘超级会员V2的分享

**Comment by Kasualix** [comment]
mods文件夹删除oculus-1.2.5.jar。
客户端不用删
晚上修

**Comment by 2080129305** [comment]
好的
