### ISSUE TITLE
关于进入阿图姆崩溃

### ISSUE THREAD

**Issue by MinorinE** [Kasualix/DTD#17]
[错误报告-2022-7-7_23.26.12.zip](https://github.com/Kasualix/DTD/files/9066843/-2022-7-7_23.26.12.zip)
删除brutalbosses mod后就可以正常进入了
咱也看不懂这个报告
阿图姆是能进的，但是进入阿图姆后一眨眼游戏就崩溃了，大概是往外加载区块的时候崩溃了

**Comment by Kasualix** [comment]
前天更新就删了。
