### ISSUE TITLE
关于龙骨箭

### ISSUE THREAD

**Issue by Galaxy-icey** [Kasualix/DTD#18]
请问一下，模组是不是把龙骨箭ban了，我做的龙骨强化长弓，龙血强化长弓，龙钢强化长弓都无法使用龙骨箭，只能使用原版箭或者特殊箭。

**Comment by Kasualix** [comment]
经过最小化测试，是[SWIAF](https://www.mcmod.cn/class/6087.html)自己的问题，[已向作者反馈](https://github.com/KreloX/SpartanFire/issues/9)。
为什么不试试斯巴达自己的箭呢，伤害是翻倍过的。
