### ISSUE TITLE
玩过一定时间的存档无法进入

### ISSUE THREAD

**Issue by LrisMirabilis** [Kasualix/DTD#4]
生存档崩溃之前创了个新的创造档测试打虚空之主，重新进入生存档就崩溃了
[crash-2022-04-15_01.50.00-server.txt](https://github.com/Kasualix/DTD/files/8491311/crash-2022-04-15_01.50.00-server.txt)

**Comment by Kasualix** [comment]
尝试删除healing campfire模组

**Comment by Kasualix** [comment]
下个版本就会删了
