### ISSUE TITLE
pcl2导入整合包失败

### ISSUE THREAD

**Issue by wxt12354** [Kasualix/DTD#8]
整合包安装失败
Caused By: 下载 Mod失败
Caused By: 输入的下载链接不正确！
   在 PCL.ModNet.LoaderDownload._Lambda$__14-0()
错误类型：System.ArgumentException
HMCL正常下载游玩。

**Comment by Kasualix** [comment]
你包从来不想支持PCL下载

**Comment by wxt12354** [comment]
woc好快的回复 明白
